// Generated by https://quicktype.io

export interface PokemonInterface {
    id: number;
    location_area_encounters: string;
    name: string;
    order: number;
    types: Type[];
}

export interface Species {
    name: string;
    url: string;
}

export interface Type {
    slot: number;
    type: Species;
}

