// Generated by https://quicktype.io

export interface TiposPokemon {
    damage_relations:      DamageRelations;
    name:                  string;
    names:                 Name[];
}

export interface DamageRelations {
    double_damage_from: Generation[];
    double_damage_to:   any[];
    half_damage_from:   any[];
    half_damage_to:     Generation[];
    no_damage_from:     Generation[];
    no_damage_to:       Generation[];
}

export interface Generation {
    name: string;
    url:  string;
}


export interface Name {
    language: Generation;
    name:     string;
}

